### ISSUE TITLE
Fehlermeldung beim Download einiger Sendungen

### ISSUE THREAD

**Issue by claell** [mediathekview/MediathekView#155]
Seit einigen Tagen bekomme ich unter Ubuntu 16.10 Fehlermeldungen beim Download einiger Sendungen.

Ich habe einen Screenshot von der Meldung erstellt:
![bildschirmfoto vom 2016-11-20 12-23-11](https://cloud.githubusercontent.com/assets/6171135/20462383/fd83b36c-af1c-11e6-8a4c-171c973a153d.png)

Das Problem tritt bei den letzten 4 Sendungen in der Liste auf dem Screenshot auf. Wenn man bei Google nach der Meldung sucht, kommen Einträge bezüglich https. Möglicherweise wurde da senderseitig kürzlich was umgestellt.

Sollten weitere Informationen oder Tests benötigt werden, stehe ich gerne bereit.

**Comment by Nicklas2751** [comment]
Das sieht so aus als wäre deine Java Version zu alt. Die kann noch keine LetsEncrypt SsL Zertifikate. Kannst du die mal updaten und schauen ob es immer noch passiert?

**Comment by claell** [comment]
Alles klar. Wie kann man denn updaten? Momentan verwende ich glaube ich einfach das in Ubuntu eingebaute, also OpenJDK.

Hatte damals einfach den Befehl aus dem Wiki ausgeführt, also `sudo apt-get install default-jre openjfx vlc flvstreamer ffmpeg`

**Comment by Nicklas2751** [comment]
Ich würde jetzt vermuten via `sudo apt-get update` und `sudo apt-get upgrade`.

**Comment by alex1702** [comment]
Hmm ubuntu 16.10 sollte eigentlich die neuste jre haben. hast du die ubuntu version durch updates oder wann wurde das letzt mal neu installiert? vllt hat ja java trotzdem nicht die neusten CAs. eventuell mal deinstallieren und neu installieren das openjdk

**Comment by claell** [comment]
@Nicklas2751 Das System ist natürlich auf dem neusten Stand.
@alex1702 Ich habe von 16.04 auf 16.10 geupgraded. Habe gerade mal `java -version ` probiert. Das liefert:
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by alex1702** [comment]
hmm die version ist aktuell. Kannst du die Links der Filme direkt aufrufen im Browser ohne probleme?

**Comment by claell** [comment]
Ja, soweit ich weiß kann ich die Links aufrufen. Damit sollte also eigentlich alles in Ordnung sein.

**Comment by claell** [comment]
Hier mal der Link zu einer Sendung: https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161118_sendung_hsh/2/161118_sendung_hsh_2328k_p35v13.mp4

**Comment by claell** [comment]
Ich habe das ganze am Wochenende auf einem anderen PC mit Ubuntu 16.10 versucht und dort hat es geklappt. Könnte also wirklich ein spezifisches Problem sein.

**Comment by alex1702** [comment]
Vielleicht war das auch ein temporäres Problem beim Sender? Nochmal an PC 1 getestet?

**Comment by claell** [comment]
Habe ich vor, momentan habe ich nur gerade Probleme mit einer neuen externen Festplatte, die defekt ist. Wenn das durch ist, teste ich nochmal!

**Comment by claell** [comment]
Problem ist immer noch präsent, also kein temporäres Problem denke ich.

**Comment by claell** [comment]
Hier mal der Log dazu, leider auch nicht wirklich aufschlussreich, denke ich.

```
#################################################################
***Programmstart***         Anzahl: 1   Gesamtdauer: 13,32 s
Konfig lesen                Anzahl: 1   Gesamtdauer: 37,00 ms
Themen in Filmliste suchen  Anzahl: 3   Gesamtdauer: 221,00 ms
Abo in Filmliste eintragen  Anzahl: 1   Gesamtdauer: 2,70 s
Blacklist filtern           Anzahl: 2   Gesamtdauer: 2,58 s
Mediensammlung erstellen    Anzahl: 1   Gesamtdauer: 1,00 ms
#################################################################

.  Proxy Authentication: not configured
.  
.  ==========================================
.  Startparameter: ./Einstellungen/.mediathek3
.  ==========================================
.  
.  
.  
.  
.  
.  
.  ___  ___         _ _       _   _          _    _   _ _               
.  |  \/  |        | (_)     | | | |        | |  | | | (_)              
.  | .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
.  | |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
.  | |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
.  \_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  
.  
.  
.  ################################################################################
.  Programmstart: 03.12.2016 11:26:18
.  ################################################################################
.  
.  totalMemory: 124 MB
.  maxMemory: 1845 MB
.  freeMemory: 98 MB
.  
.  ################################################################################
.  
.  MediathekView 12 [Rel: 13.840]
.  Compiled: 08.08.2016 / 15:51:19
.  
.  ################################################################################
.  
.  Java
.  Vendor: Oracle Corporation
.  VMname: OpenJDK 64-Bit Server VM
.  Version: 1.8.0_111
.  Runtimeversion: 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14
.  
.  Programmpfad: /media/clel/Programme/MediathekView 12/
.  Verzeichnis Einstellungen: ./Einstellungen/.mediathek3
.  
.  ################################################################################
.  
.  

========== ========== ========== ========== ==========
DURATION 0:  Start  [263,00 ms]
   Klasse:  Main.lambda$main$1
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 1:  Konfig lesen  [38,00 ms]
   Klasse:  Daten.load
   Konfig lesen Anzahl: 1   Dauer: 36,00 ms
========== ========== ========== ========== ==========

.  Konfig wurde gelesen!

========== ========== ========== ========== ==========
DURATION 2:  Start Gui  [35,00 ms]
   Klasse:  Main.lambda$main$1
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 3:  Init GUI  [622,00 ms]
   Klasse:  Main.lambda$main$1
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 4:  Gui steht!  [214,00 ms]
   Klasse:  Main.lambda$main$1
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 5:  Programmstart Daten laden  [1,00 ms]
   Klasse:  Thread.run
========== ========== ========== ========== ==========

.  Liste Filme lesen von: ./Einstellungen/.mediathek3/filme.json
.  Liste Filme gelesen am: 03.12.2016, 11:26
.    erstellt am: 03.12.2016, 09:32
.    Anzahl Filme: 138215
.  Liste Filme gelesen am: 03.12.2016, 11:26
.    erstellt am: 03.12.2016, 09:32
.    Anzahl Filme: 138215
.    Anzahl Neue: 9170
.  Die Filmliste ist 113 Minuten alt

========== ========== ========== ========== ==========
DURATION 6:  Themen in Filmliste suchen  [807,00 ms]
   Klasse:  ProgStart$loadFilmlistProgStart_.run
   Themen in Filmliste suchen Anzahl: 1   Dauer: 106,00 ms
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 7:  Abo in Filmliste eintragen  [3,22 s]
   Klasse:  ProgStart$loadFilmlistProgStart_.run
   Abo in Filmliste eintragen Anzahl: 1   Dauer: 3,22 s
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 8:  Themen in Filmliste suchen  [76,00 ms]
   Klasse:  ListeBlacklist.filterListe
   Themen in Filmliste suchen Anzahl: 2   Dauer: 66,00 ms
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 9:  Blacklist filtern  [0,00 ms]
   Klasse:  ListeBlacklist.filterListe
   Blacklist filtern Anzahl: 1   Dauer: 76,00 ms
========== ========== ========== ========== ==========

.  -------------------------------------------------------
.  Einstellungen sichern
.  Einstellungen wurden heute schon gesichert
.  -------------------------------------------------------
.  Daten Schreiben nach: ./Einstellungen/.mediathek3/mediathek.xml
.  Start Schreiben nach: /media/clel/Programme/MediathekView 12/./Einstellungen/.mediathek3/mediathek.xml
.  geschrieben!

========== ========== ========== ========== ==========
DURATION 10:  CheckUpdate  [2,92 s]
   Klasse:  FilmeLaden.lambda$notifyFertig$6
========== ========== ========== ========== ==========

.  MediaDB schreiben (0 Dateien) :
.     --> Start Schreiben nach: ./Einstellungen/.mediathek3/mediadb.txt
.     --> geschrieben!

========== ========== ========== ========== ==========
DURATION 11:  Mediensammlung erstellen  [5,00 ms]
   Klasse:  Thread.run
   Mediensammlung erstellen Anzahl: 1   Dauer: 1,00 ms
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 12:  ***Programmstart***  [3,39 s]
   Klasse:  JTabbedPane.fireStateChanged
   ***Programmstart*** Anzahl: 1   Dauer: 11,60 s
========== ========== ========== ========== ==========

. ---------------------------------------
. | Download starten
. | Programmset: Linux Fernsehformate Titel
. | Ziel: /media/clel/Transcend Multimedia/Filme/Mediathek/Fernsehformate/Sketch History/Sketch History - die neue Staffel - 2016-12-02 (ZDF).mp4
. | URL: https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161121_sendung_ske/2/161121_sendung_ske_3296k_p15v13.mp4
. | Startzeit: 11:26:33
. | direkter Download
. ---------------------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at mediathek.controller.starter.StarterClass$DirectHttpDownloadThread.getContentLength(StarterClass.java:715)
	at mediathek.controller.starter.StarterClass$DirectHttpDownloadThread.run(StarterClass.java:841)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 15 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 21 more

* Fehlernr: 643298301
* Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
* Fehler(MSearch): StarterClass$DirectHttpDownloadThread.getContentLength

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at mediathek.controller.starter.StarterClass$DirectHttpDownloadThread.run(StarterClass.java:849)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 11 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 17 more

* Fehlernr: 316598941
* Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
* Fehler(MSearch): StarterClass$DirectHttpDownloadThread.run
*           Fehler

. ---------------------------------------
. | Download ist fertig und war fehlerhaft
. | Programmset: Linux Fernsehformate Titel
. | Ziel: /media/clel/Transcend Multimedia/Filme/Mediathek/Fernsehformate/Sketch History/Sketch History - die neue Staffel - 2016-12-02 (ZDF).mp4
. | Startzeit: 11:26:33
. | Endzeit: 11:26:33
. | Dauer: 0 s
. | Dauer: <1 Min.
. | URL: https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161121_sendung_ske/2/161121_sendung_ske_3296k_p15v13.mp4
. | direkter Download
. ---------------------------------------
.  Daten Schreiben nach: ./Einstellungen/.mediathek3/mediathek.xml
.  Start Schreiben nach: /media/clel/Programme/MediathekView 12/./Einstellungen/.mediathek3/mediathek.xml
.  geschrieben!

========== ========== ========== ========== ==========
DURATION 13:  Themen in Filmliste suchen  [23,85 s]
   Klasse:  ListeBlacklist.filterListe
   Themen in Filmliste suchen Anzahl: 3   Dauer: 42,00 ms
========== ========== ========== ========== ==========


========== ========== ========== ========== ==========
DURATION 14:  Blacklist filtern  [0,00 ms]
   Klasse:  ListeBlacklist.filterListe
   Blacklist filtern Anzahl: 2   Dauer: 2,34 s
========== ========== ========== ========== ==========

.  Daten Schreiben nach: ./Einstellungen/.mediathek3/mediathek.xml
.  Start Schreiben nach: /media/clel/Programme/MediathekView 12/./Einstellungen/.mediathek3/mediathek.xml
.  geschrieben!
.  
.  
.  
.  
.  
.  ################################################################################
.  Ex! StarterClass$DirectHttpDownloadThread.getContentLength  Fehlernummer: 643298301 Anzahl: 1
.  Ex! StarterClass$DirectHttpDownloadThread.run               Fehlernummer: 316598941 Anzahl: 1
.  ################################################################################
.  
.  
.  ################################################################################
.     --> Beginn: 03.12.2016 11:26:18
.     --> Fertig: 03.12.2016 11:26:57
.     --> Dauer[Min]: <1
.  ################################################################################
.  
.     und Tschuess
.  
.  
.  ################################################################################


#################################################################
***Programmstart***         Anzahl: 1   Gesamtdauer: 11,60 s
Konfig lesen                Anzahl: 1   Gesamtdauer: 36,00 ms
Themen in Filmliste suchen  Anzahl: 3   Gesamtdauer: 214,00 ms
Abo in Filmliste eintragen  Anzahl: 1   Gesamtdauer: 3,22 s
Blacklist filtern           Anzahl: 2   Gesamtdauer: 2,42 s
Mediensammlung erstellen    Anzahl: 1   Gesamtdauer: 1,00 ms
#################################################################
```

**Comment by claell** [comment]
Problem ist behoben. 
Ich vermute, dass ein Zusammenhang mit https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760 besteht. Ich hatte auf dem PC Ubuntu 15.10 installiert und dann immer geupgradet gehabt. Dadurch war vermutlich dieser Bug noch als Altlast enthalten.

Habe dann das entsprechende Paket neu installiert, musste aber vermutlich noch neustarten, damit dann alles angewendet wurde. Läuft jetzt jedenfalls.

**Comment by alex1702** [comment]
sowas hab ich mir ja irgendwie gedacht. Blöder Fehler.

**Comment by claell** [comment]
Ja, schon ärgerlich aber immerhin jetzt behoben :)
