### ISSUE TITLE
Javafehler beim drücken des Hilfe Buttons mittig auf dem Filmlistenscreen

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#175]
![auswahl_001](https://cloud.githubusercontent.com/assets/1862815/21000474/62e50b8c-bd1b-11e6-95ea-8b98e639ed81.png)

Fehler:
https://p.elaon.de/VczrH/
```
07:42:03.718 [ERROR] [system.err] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
07:42:03.718 [ERROR] [system.err]       at mediathek.file.GetFile.getHilfeSuchen(GetFile.java:54)
07:42:03.718 [ERROR] [system.err]       at mediathek.gui.MVFilterPanel.lambda$new$1(MVFilterPanel.java:93)
07:42:03.718 [ERROR] [system.err]       at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
07:42:03.718 [ERROR] [system.err]       at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
07:42:03.718 [ERROR] [system.err]       at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
07:42:03.719 [ERROR] [system.err]       at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
07:42:03.719 [ERROR] [system.err]       at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
07:42:03.719 [ERROR] [system.err]       at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
07:42:03.719 [ERROR] [system.err]       at java.awt.Component.processMouseEvent(Component.java:6533)
07:42:03.719 [ERROR] [system.err]       at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
07:42:03.719 [ERROR] [system.err]       at java.awt.Component.processEvent(Component.java:6298)
07:42:03.719 [ERROR] [system.err]       at java.awt.Container.processEvent(Container.java:2236)
07:42:03.719 [ERROR] [system.err]       at java.awt.Component.dispatchEventImpl(Component.java:4889)
07:42:03.719 [ERROR] [system.err]       at java.awt.Container.dispatchEventImpl(Container.java:2294)
07:42:03.719 [ERROR] [system.err]       at java.awt.Component.dispatchEvent(Component.java:4711)
07:42:03.719 [ERROR] [system.err]       at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
07:42:03.719 [ERROR] [system.err]       at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
07:42:03.719 [ERROR] [system.err]       at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
07:42:03.720 [ERROR] [system.err]       at java.awt.Container.dispatchEventImpl(Container.java:2280)
07:42:03.720 [ERROR] [system.err]       at java.awt.Window.dispatchEventImpl(Window.java:2746)
07:42:03.720 [ERROR] [system.err]       at java.awt.Component.dispatchEvent(Component.java:4711)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue.access$500(EventQueue.java:97)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue$3.run(EventQueue.java:709)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue$3.run(EventQueue.java:703)
07:42:03.720 [ERROR] [system.err]       at java.security.AccessController.doPrivileged(Native Method)
07:42:03.720 [ERROR] [system.err]       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
07:42:03.720 [ERROR] [system.err]       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue$4.run(EventQueue.java:731)
07:42:03.720 [ERROR] [system.err]       at java.awt.EventQueue$4.run(EventQueue.java:729)
07:42:03.720 [ERROR] [system.err]       at java.security.AccessController.doPrivileged(Native Method)
07:42:03.721 [ERROR] [system.err]       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
07:42:03.721 [ERROR] [system.err]       at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Nicklas2751** [comment]
develop oder master branch betroffen?

**Comment by Nicklas2751** [comment]
Aaah da sind lauter non Java Datein die werden beim bauen natürlich nicht mit zu class datein und müssen folglich in den resources ordner. Fix ich. ;)
