### ISSUE TITLE
Das Laden der Filmliste hat nicht geklappt

### ISSUE THREAD

**Issue by hurzl** [mediathekview/MediathekView#303]
mit 13.0.6:

```
...

.  Filmliste laden von: http://th16016-web333.server49.vorschauseite.eu/filme/Filmliste-akt.xz
.  Liste Filme lesen von: http://th16016-web333.server49.vorschauseite.eu/filme/Filmliste-akt.xz
.  Liste Filme gelesen am: 07.03.2018, 07:57
.    erstellt am: 30.04.2017, 10:14
.    Anzahl Filme: 0
.  Filmliste laden von: http://wp12495408.server-he.de/filme/Filmliste-akt.xz
.  Liste Filme lesen von: http://wp12495408.server-he.de/filme/Filmliste-akt.xz
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
java.net.UnknownHostException: wp12495408.server-he.de: hostname nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)

...
```

die erste "erstellt am: 30.04.2017", die zweite UnknownHost?

**Comment by alex1702** [comment]
Das sind beides keine Server von uns. Hast du MV von unserer Seite runter geladen?

**Comment by hurzl** [comment]
Hatte vorher 13.0.1, und diese hatte ich gelöscht.

**Comment by alex1702** [comment]
Auch den Einstellungsordner ".mediathek3" gelöscht in deinem Home-Verzeichnis?

**Comment by hurzl** [comment]
s.o. ;)

**Comment by hurzl** [comment]
anscheinend waren doch irgendwelche Reste übriggeblieben :(

**Comment by xaverW** [comment]
in den "alten" Filmlisten ist die Adresse auch nicht, die habe ich schon vor längerem angepasst:
http://zdfmediathk.sourceforge.net/akt.xml
http://zdfmediathk.sourceforge.net/diff.xml
