### ISSUE TITLE
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by kradan** [mediathekview/MediathekView#308]
Auf Debian Buster kann mediathekview keine Filme herunter laden oder sich selbst aktualisieren

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameter
Exception: the trustAnchors parameter must be non-empty
        at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1436)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsU
RLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java
:245)
        at mediathek.daten.ListePsetVorlagen.loadListOfSets(ListePsetVorlagen.java:152)
        at mediathek.daten.ListePsetVorlagen.getStandarset(ListePsetVorlagen.java:97)
        at mediathek.update.CheckUpdate.lambda$checkForPsetUpdates$1(CheckUpdate.java:100)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDoma
in.java:89)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:881)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:677)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:648
        at mediathek.update.ProgrammUpdateSuchen.lambda$checkVersion$0(ProgrammUpdateSuchen.java:62)             
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)        
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)            
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)                      
        at java.base/java.security.AccessController.doPrivileged(Native Method)            
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDoma
in.java:89)                                                                                   
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)                                           at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)       
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)   
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                    
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)  
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the tr
ustAnchors parameter must be non-empty                                                    
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)  
        at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
        at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:330)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:180)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:192)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
        at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)              
        at java.base/sun.security.ssl.ClientHandshaker.certificateStatus(ClientHandshaker.java:1798)
        at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:276)
        at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1092)                       
        at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)                  
        at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)       
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074) 
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)  
        at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
        ... 44 more                                                                     
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) 
        at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
        ... 59 more                                                                            
                                                                                       
* Fehlernr: 398001963                                                                 
* Exception: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the
trustAnchors parameter must be non-empty                                                   
* Fehler(MSearch): ListePsetVorlagen.loadListOfSets

$ java --version
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+12-Debian-2)
OpenJDK Server VM (build 9.0.4+12-Debian-2, mixed mode)

$ update-alternatives --display java
java - automatischer Modus
  beste Version des Links ist /usr/lib/jvm/java-9-openjdk-i386/bin/java
  Link verweist zur Zeit auf /usr/lib/jvm/java-9-openjdk-i386/bin/java
  Link java ist /usr/bin/java
  Slave java.1.gz ist /usr/share/man/man1/java.1.gz
/usr/lib/jvm/java-9-openjdk-i386/bin/java - Priorität 1091
  Slave java.1.gz: /usr/lib/jvm/java-9-openjdk-i386/man/man1/java.1.gz

ia$ apt-cache policy ca-certificates-java
ca-certificates-java:
  Installiert:           20170930
  Installationskandidat: 20170930
  Versionstabelle:
 *** 20170930 500
        500 http://ftp.de.debian.org/debian buster/main i386 Packages
        100 /var/lib/dpkg/status
kdn@t43:~/media$ dpkg -l | grep openjdk
ii  openjdk-9-jre:i386                    9.0.4+12-2                     i386         OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-9-jre-headless:i386           9.0.4+12-2                     i386         OpenJDK Java runtime, using Hotspot JIT (headless)
kdn@t43:~/media$ ls -al /etc/ssl/certs/java/
insgesamt 400
drwxr-xr-x 2 root root   4096 Mär 28 03:28 .
drwxr-xr-x 3 root root  20480 Mär 28 03:32 ..
-rw-r--r-- 1 root root 191820 Mär 28 03:32 cacerts
-rw-r--r-- 1 root root 190964 Mär 28 03:28 cacerts.dpkg-old
```

vgl https://forum.ubuntuusers.de/topic/java-fehler-javax-net-ssl-sslhandshakeexceptio/

Lösungsvorschläge
- http://www.techpaste.com/2017/03/trustanchors-parameter-must-non-empty/
- https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

**Comment by pidoubleyou** [comment]
@kradan Die Fehlermeldung weißt auf ein Problem auf deinem System hin. Da können wir seitens MV leider nichts anpassen. 

Hast du denn die verschiedenen Lösungsvorschläge im StackOverflow-Link erfolglos ausprobiert?
