### ISSUE TITLE
Portabler Modus [macOS]

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#348]
Für Tests finde ich den portable Modus sehr sinnvoll und brauchbar; so muss man nicht seine eigenen Einstellungen verwerfen bzw. verändern.

Mit "MV 13.2. beta 2" sollte der portable Modus (wie bis und MV 13.0.6) wieder funktionieren. Zumindest unter macOS (El Cap) und mit den Programm-Dateien, die in der ZIP-Downloaddatei von 13.1.3 vorliegen (jar-Datei natürlich ersetzt), scheint das nicht zu funktionieren: Da wird u.a. immer noch gemeldet, dass ein absoluter Pfad benötigt wird:

```
. Startparameter: Einstellungen/.mediathek3
. Portable Mode: true
. Proxy Authentication: not configured
. Programmstart: 25.08.2018 14:40:17
. maxMemory: 3817 MB
. Version: MediathekView 13.2.0
. Java:
. Vendor: Oracle Corporation
. VMname: Java HotSpot(TM) 64-Bit Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-b13
. Programmpfad: /Users/user/Documents/t-e-m-p/MediathekView-13.1.3/
. Verzeichnis Einstellungen: Einstellungen/.mediathek3
[…]
. ========== ========== ========== ========== ==========
. DURATION 4:  Start Gui  [5.01 s]
.    Klasse:  MediathekGuiMac.<init>
. ========== ========== ========== ========== ==========
. initializeDatabase()
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:Einstellungen/.mediathek3/database/mediathekview;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:388)
	at org.h2.engine.Engine.openSession(Engine.java:50)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:92)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:291)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:883)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:436)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:365)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at mSearch.daten.PooledDatabaseConnection.getConnection(PooledDatabaseConnection.java:54)
	at mSearch.daten.DatenFilm$Database.initializeDatabase(DatenFilm.java:637)
	at mSearch.daten.DatenFilm$Database.access$000(DatenFilm.java:607)
	at mSearch.daten.DatenFilm.<clinit>(DatenFilm.java:107)
	at mediathek.tool.table.MVFilmTable.setupTableType(MVFilmTable.java:15)
	at mediathek.tool.table.MVTable.<init>(MVTable.java:68)
	at mediathek.tool.table.MVFilmTable.<init>(MVFilmTable.java:9)
	at mediathek.gui.GuiFilme.<init>(GuiFilme.java:92)
	at mediathek.MediathekGui.initTabs(MediathekGui.java:568)
	at mediathek.MediathekGui.init(MediathekGui.java:487)
	at mediathek.MediathekGui.<init>(MediathekGui.java:208)
	at mediathek.mac.MediathekGuiMac.<init>(MediathekGuiMac.java:29)
	at mediathek.Main.getPlatformWindow(Main.java:290)
	at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at mediathek.tool.table.MVFilmTable.setupTableType(MVFilmTable.java:15)
	at mediathek.tool.table.MVTable.<init>(MVTable.java:68)
	at mediathek.tool.table.MVFilmTable.<init>(MVFilmTable.java:9)
	at mediathek.gui.GuiFilme.<init>(GuiFilme.java:92)
	at mediathek.MediathekGui.initTabs(MediathekGui.java:568)
	at mediathek.MediathekGui.init(MediathekGui.java:487)
	at mediathek.MediathekGui.<init>(MediathekGui.java:208)
	at mediathek.mac.MediathekGuiMac.<init>(MediathekGuiMac.java:29)
	at mediathek.Main.getPlatformWindow(Main.java:290)
	at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at mSearch.daten.DatenFilm$Database.initializeDatabase(DatenFilm.java:638)
	at mSearch.daten.DatenFilm$Database.access$000(DatenFilm.java:607)
	at mSearch.daten.DatenFilm.<clinit>(DatenFilm.java:107)
	... 24 more

```

**Comment by derreisende77** [comment]
Ist im Release gefixed
