### ISSUE TITLE
MediathekView startet nicht: Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task

### ISSUE THREAD

**Issue by media233** [mediathekview/MediathekView#357]
Wenn ich MediathekView starten will, bekomme ich folgenden Fehler:

```
$ java -jar MediathekView.jar

___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  


. Portable Mode: false
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mediathek.Main.setupPortableMode(Main.java:149)
	at mediathek.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

Java Version

```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by derreisende77** [comment]
kein openjfx installiert?

**Comment by kvbroten** [comment]
Figured it out! /usr/bin/java was pointing to Java 11 executable, MediathekView needs Version 8: 

$ which java
/usr/bin/java

$ ls -la /usr/bin/java
lrwxrwxrwx 1 root root 22 Nov  1  2016 /usr/bin/java -> /etc/alternatives/java

$ ls -la /etc/alternatives/java
lrwxrwxrwx 1 root root 43 May 29 07:18 /etc/alternatives/java -> /usr/lib/jvm/java-11-openjdk-amd64/bin/java

$ cd /home/<username>/bin/Mediathekview/

$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar MediathekView.jar

--> MediathekView starts! :)

**Comment by derreisende77** [comment]
Latest MediathekView checks if you are using wrong Java version..

**Comment by cfi** [comment]
Hating mee-too's, I'm stuck after what kvbroten already found out. Therefore I'm reluctant to create this as a new issue. Let me know if I should:
Ubuntu 18.10. Default java is version 11.
Same commands, same output, but Mediathekview does not start, missing javafx.concurrent.Task

$ which java
/usr/bin/java
$ ls -la /usr/bin/java
lrwxrwxrwx 1 root root 22 Okt 25 19:57 /usr/bin/java -> /etc/alternatives/java
$ ls -la /etc/alternatives/java
lrwxrwxrwx 1 root root 43 Okt 25 19:56 /etc/alternatives/java -> /usr/lib/jvm/java-11-openjdk-amd64/bin/java

After downloading latest version from
  https://download.mediathekview.de/stabil/MediathekView-latest.tar.gz
and cd'ing into untarred Download area:
~/Downloads/MediathekView$ ls
bin  Icons  lib  MediathekView.command  MediathekView.exe  MediathekView.ico  MediathekView_ipv4.exe  MediathekView.jar  MediathekView_Portable.exe  MediathekView.sh  README.txt
~/Downloads/MediathekView$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar MediathekView.jar
```





___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  


. Portable Mode: false
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at mediathek.Main.setupPortableMode(Main.java:149)
        at mediathek.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```

Is this a problem, too?```

$ dpkg -l openjfx
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                                     Version                   Architektur               Beschreibung
+++-========================================-=========================-=========================-=====================================================================================
ii  openjfx                                  11+26-4                   amd64                     JavaFX/OpenJFX - Rich client application platform for Java
```

**Comment by cfi** [comment]
Checksum, to be on the safe side regarding the version:
```
$ md5sum *
md5sum: bin: Is a directory
md5sum: Icons: Is a directory
md5sum: lib: Is a directory
cfc0c2abd9a4bba2d5ac8f0569d668fd  MediathekView.command
94ef7944d93e15c522395b513c10b586  MediathekView.exe
a6b27f26df29309bdfa3327c55d40850  MediathekView.ico
d4413a0b96e7526bef995c241638a12e  MediathekView_ipv4.exe
6b3d51487cd66331a726d8e26ee1821e  MediathekView.jar
d6a054b0f80b2633d78ec7b58e6bed95  MediathekView_Portable.exe
8974439ab814655614bcd1cf13c24ce9  MediathekView.sh
8e7b694d761fbd4d45a13ccebb71bb69  README.txt
```

**Comment by derreisende77** [comment]
As stated several times in the forum and in the release notes MV is NOT compatible with Java 9+ yet. You nees Java 8

**Comment by cfi** [comment]
Yes, I know. That's why I used the ocmmand

`/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar MediathekView.jar`

Do you think that there's still some other version picked up?

**Comment by scmmmh** [comment]
Ubuntu issue with Java8 and OpenJFX 11: https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946

**Comment by cfi** [comment]
Makes sense. Thanks for pointing that out!

Interestingly Ubuntu 18.04 seems to be fine to some extent: I cannot run the Ubuntu provided package of mediathekview, but I can run the downloaded one.
On my newer 18.10 machine neither of them work.

**Comment by derreisende77** [comment]
we don´t provide the ubuntu package AFAIK. we only officially support the downloads from our homepage

**Comment by cfi** [comment]
Unfortunately the downloaded package is affected by this as well as I had to learn after installing Ubuntu 18.10. Anyway this is either in the Ubuntu domain or in the packager's. Thanks!

**Comment by scmmmh** [comment]
The problem is with the openjfx package which comes with 18.10 and is for java 11. Thus the java 8 installation does not have access to the openjfx packages and thus MediathekView dies.

Download the Java8 JRE from here: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html. Then run MediathekView with the java executable provided by that file.

**Comment by Strubbl** [comment]
Got the same error today. In Archlinux openjdk-8 does not work anymore. I installed jre8 from Aur to make it work again.
