### ISSUE TITLE
MediathekView 13 startet nicht unter Ubuntu 18.04

### ISSUE THREAD

**Issue by errotu** [mediathekview/MediathekView#359]
Leider startet MediathekView nicht mehr bei mir.

Beim Starten über die Konsole erhalte ich die folgende Fehlermeldung:
```
.  Proxy Authentication: not configured
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1312)
	at mediathek.Main.startGuiMode(Main.java:153)
	at mediathek.Main.startUI(Main.java:145)
	at mediathek.Main.start(Main.java:129)
	at mediathek.Main.main(Main.java:116)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 17 more

```

Die installierte Version ist 13.0.6-1. Ich habe sowohl OpenJDK als auch die Java Version von Oracle ausprobiert. Die Fehlermeldungen sind identisch.
```
java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by derreisende77** [comment]
https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror#723503

Evtl hilft die Lösung mit dem editieren der Datei. Ist aber kein Fehler von MediathekView. 
Ansonsten wende dich bitte an das Forum.

**Comment by errotu** [comment]
MediathekView funktioniert nun wieder, nachdem ich via 

> sudo update-alternatives --config java

auf das java-11-openjdk-Paket umgestellt und danach entsprechend der verlinkten Lösung

> assistive_technologies=org.GNOME.Accessibility.AtkWrapper

aus der 

> /etc/java-11-openjdk/accessibility.properties

zu

> #assistive_technologies=org.GNOME.Accessibility.AtkWrapper

verändert und damit auskommentiert habe.
Vielen Dank!

**Comment by derreisende77** [comment]
MV versionen neuer als 13.1 funktionieren NICHT mit Java 11. Der Start wird auch unterbunden. Bitte das beachten!
