### ISSUE TITLE
SQLException and JdbcSQLException 

### ISSUE THREAD

**Issue by HJarausch** [mediathekview/MediathekView#361]
I get LOTS of SQLException and JdbcSQLException with all version newer than 13.0.6
like

. SQLException: 
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.message.DbException.get(DbException.java:144) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.engine.Session.getTransaction(Session.java:1686) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.engine.Session.getStatementSavepoint(Session.java:1696) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.engine.Session.setSavepoint(Session.java:859) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Command.executeUpdate(Command.java:255) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153) ~[h2-1.4.197.jar:1.4.197]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.5.0.jar:2.5.0]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.5.0.jar:2.5.0]
        at mSearch.daten.DatenFilm.writeFilmNumberToDatabase(DatenFilm.java:173) [MediathekView.jar:?]
        at mSearch.daten.DatenFilm.<init>(DatenFilm.java:163) [MediathekView.jar:?]
        at mSearch.filmlisten.reader.FilmListReader.readData(FilmListReader.java:262) [MediathekView.jar:?]
        at mSearch.filmlisten.reader.FilmListReader.processFromFile(FilmListReader.java:367) [MediathekView.jar:?]
        at mSearch.filmlisten.reader.FilmListReader.readFilmListe(FilmListReader.java:320) [MediathekView.jar:?]
        at mediathek.tool.threads.UIFilmlistLoaderThread.readLocalFilmList(UIFilmlistLoaderThread.java:59) [MediathekView.jar:?]
        at mediathek.tool.threads.UIFilmlistLoaderThread.run(UIFilmlistLoaderThread.java:91) [MediathekView.jar:?]

---

. JdbcSQLException: 
org.h2.jdbc.JdbcSQLException: Table "DESCRIPTION" not found; SQL statement:
MERGE INTO mediathekview.description KEY(ID) VALUES (?,?) [42102-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.schema.Schema.getTableOrView(Schema.java:506) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.readTableOrView(Parser.java:5903) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.readTableOrView(Parser.java:5897) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.readSimpleTableFilter(Parser.java:838) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.parseMerge(Parser.java:1080) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.parsePrepared(Parser.java:437) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.parse(Parser.java:335) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.parse(Parser.java:307) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.command.Parser.prepareCommand(Parser.java:278) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.engine.Session.prepareLocal(Session.java:611) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.engine.Session.prepareCommand(Session.java:549) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76) ~[h2-1.4.197.jar:1.4.197]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304) ~[h2-1.4.197.jar:1.4.197]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292) ~[commons-dbcp2-2.5.0.jar:2.5.0]
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292) ~[commons-dbcp2-2.5.0.jar:2.5.0]
        at mSearch.daten.DatenFilm.writeDescriptionToDatabase(DatenFilm.java:389) ~[MediathekView.jar:?]
        at mSearch.daten.DatenFilm.lambda$setDescription$0(DatenFilm.java:319) ~[MediathekView.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
. org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]

I have Java Oracle 1.8.0.181 installed on my Gentoo Linux system here.
What am I missing?
Thanks for a hint.

**Comment by HJarausch** [comment]
Thanks!
