### ISSUE TITLE
--auto geht nicht mehr.

### ISSUE THREAD

**Issue by JPRuehmann** [mediathekview/MediathekView#367]
Hallo
Bisher habe ich immer mediathekview --auto als chronjob benutzt um meine Abo´s täglich automatisc herunterzuladen.
Das geht jetzt nicht mehr, warum. Und wie kann ich das wieder zum laufen bringen?

```
| \/ | | (_) | | | | | | | | | (_) 
| . . | ___ __| |_ __ _| |_| |__ ___| | _| | | |_ _____ __ 
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / / 
| | | | __/ (_| | | (_| | |_| | | | __/ <\ \_/ / | __/\ V V / 
\_| |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/ 


. Startparameter: -auto 
. Portable Mode: false 
. Proxy Authentication: not configured 
. java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it. 
. Programmstart: 17.09.2018 05:00:05 
. maxMemory: 954 MB 
. Version: MediathekView 13.2.0 
. Java: 
. Vendor: Oracle Corporation 
. VMname: Java HotSpot(TM) Server VM 
. Version: 1.8.0_152-ea 
. Runtimeversion: 1.8.0_152-ea-b05 
. Programmpfad: /usr/share/mediathekview/ 
. Verzeichnis Einstellungen: /home/ruehmann/.mediathek3 
. 
. 
. 
. Einstellungen laden: /home/ruehmann/.mediathek3/mediathek.xml 
. 
. ======================================= 
. Systemparameter 
. ----------------- 
. Download-Timeout [s]: 250 
. max. Download-Restart: 5 
. max. Download-Restart-Http: 10 
. Download weiterführen in [s]: 60 
. Download Fehlermeldung anzeigen [s]: 120 
. Downoadprogress anzeigen: true 
Exception in thread "DummyFXApp Thread" java.lang.UnsupportedOperationException: Unable to open DISPLAY 
at com.sun.glass.ui.gtk.GtkApplication.(GtkApplication.java:68) 
at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41) 
at com.sun.glass.ui.Application.run(Application.java:146) 
at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257) 
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211) 
at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675) 
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695) 
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182) 
at java.lang.Thread.run(Thread.java:748) 
. User-Agent: MediathekView 
. ======================================= 
. 
. Liste Filme lesen von: /home/ruehmann/.mediathek3/filme.json 
. initializeDatabase() 
. initializeDatabase() done. 
. Creating SQL indices 
. Finished creating SQL indices 
. Liste Filme gelesen am: 17.09.2018, 05:01 
. erstellt am: 16.09.2018, 20:15 
. Anzahl Filme: 249490 
. Die Filmliste ist 525 Minuten alt 
. Neue Filmliste laden 
. MVHttpClient: Proxy not configured 
. 
. Alte Liste erstellt am: 16.09.2018, 20:15 
. Anzahl Filme: 249490 
. Anzahl Neue: 2546 
. Filmliste laden (auto) 
. Filmliste laden von: http://verteiler1.mediathekview.de/Filmliste-akt.xz 
. Liste Filme lesen von: http://verteiler1.mediathekview.de/Filmliste-akt.xz 
. Creating SQL indices 
. Finished creating SQL indices 
. Liste Filme gelesen am: 17.09.2018, 05:02 
. erstellt am: 16.09.2018, 23:17 
. Anzahl Filme: 251382 
. Die Filmliste ist 344 Minuten alt 
. Filmliste zu alt, neuer Versuch 
. Filmliste laden von: http://verteiler6.mediathekview.de/Filmliste-akt.xz 
. Liste Filme lesen von: http://verteiler6.mediathekview.de/Filmliste-akt.xz 
. Creating SQL indices 
. Finished creating SQL indices 
. Liste Filme gelesen am: 17.09.2018, 05:04 
. erstellt am: 16.09.2018, 23:17 
. Anzahl Filme: 251382 
. 
. Liste Kompl. gelesen am: 17.09.2018, 05:04 
. Liste Kompl erstellt am: 16.09.2018, 23:17 
. Anzahl Filme: 251382 
. Filme schreiben (251382 Filme) : 
. --> Start Schreiben nach: /home/ruehmann/.mediathek3/filme.json 
. --> geschrieben! 
. Write duration: 80136 ms 
. 
. Jetzige Liste erstellt am: 16.09.2018, 23:17 
. Anzahl Filme: 251382 
. Anzahl Neue: 1888 
```

Ich benutze Kubuntu 16.04 LTS (32Bit) und Java 8.

**Comment by frankconrad** [comment]
diese Version funktioniert:
. Java:
. Vendor: Oracle Corporation
. VMname: Java HotSpot(TM) 64-Bit Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-b13

**Comment by JPRuehmann** [comment]
Keine änderung funktioniert nach wie vor nicht im Hintergrund, ohne X (als Cronjob).

**Comment by derreisende77** [comment]
Starte den client mit meiner Version bitte so n CRON: `java -Xmx768M -jar Mediathekview.jar -auto`

**Comment by JPRuehmann** [comment]
`/opt/java/32/jdk1.8.0_152/bin/java -Xmx768M -jar /usr/share/mediathekview/Mediathekview.jar -auto`

geht gar nicht.

`Error: Unable to access jarfile /usr/share/mediathekview/Mediathekview.jar
`

**Comment by derreisende77** [comment]
1. Zugriffrechte passen nicht. Das ist kein Fehler des Programms sondern von Linux.
2. jdk1.8.0_152 ist völlig veraltet. Es ist bekannt das es bei Versionen vor _172 zu Fehlern im Programm kommt. Derzeit aktuell ist jdk1.8.0_181

**Comment by JPRuehmann** [comment]
Vielleicht sollte mann lesen, ;-)
MediathekView.jar nicht Mediathekview.jar

**Comment by JPRuehmann** [comment]
Danke

Jetzt geht es wieder.

**Comment by Dave3o3** [comment]
Kann ich auch bestätigen; auch ohne `-Xmx768M` Argument :)

**Comment by JPRuehmann** [comment]
Meine aktuelle Version ist eigentlich jdk9+181.

**Comment by holgis** [comment]
Ich kann bestätigen dass diese Version

> Bitte mal [diese Version](https://www.dropbox.com/s/kn6kpo9nkbl42v8/MediathekView.jar?dl=0) herunterladen, die vorhandene Datei ersetzen und damit testen. Sollte dies die Fehler beheben werde ich ein Update herausbringen.

mein Problem aus issue #330 behebt.
