### ISSUE TITLE
Recent versions don't run with OpenJDK on Wayland

### ISSUE THREAD

**Issue by erAck** [mediathekview/MediathekView#374]
Using OpenJDK version 1.8.0_181 with OpenJFX 8.0.152 on Fedora 27 with Wayland, the latest version of MediathekView I get running is 13.0.6
All later versions from 13.1.0 up to 13.2.1 fail to start with a Graphics Device initialization failure, 13.2.1 even hangs after that, earlier versions just quit.
The error output is
```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
	at javafx.animation.Animation.<init>(Animation.java:1029)
	at javafx.animation.Transition.<init>(Transition.java:151)
	at javafx.animation.PauseTransition.<init>(PauseTransition.java:142)
	at mSearch.tool.ApplicationConfiguration$EvtListener.<init>(ApplicationConfiguration.java:83)
	at mSearch.tool.ApplicationConfiguration.setupXmlConfiguration(ApplicationConfiguration.java:104)
	at mSearch.tool.ApplicationConfiguration.<init>(ApplicationConfiguration.java:65)
	at mSearch.tool.ApplicationConfiguration.<clinit>(ApplicationConfiguration.java:58)
	at mediathek.MediathekGui.<init>(MediathekGui.java:1006)
	at mediathek.Main.getPlatformWindow(Main.java:297)
	at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at mediathek.MediathekGui.<init>(MediathekGui.java:1006)
	at mediathek.Main.getPlatformWindow(Main.java:297)
	at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:217)
	at javafx.animation.Animation.<init>(Animation.java:1029)
	at javafx.animation.Transition.<init>(Transition.java:151)
	at javafx.animation.PauseTransition.<init>(PauseTransition.java:142)
	at mSearch.tool.ApplicationConfiguration$EvtListener.<init>(ApplicationConfiguration.java:83)
	at mSearch.tool.ApplicationConfiguration.setupXmlConfiguration(ApplicationConfiguration.java:104)
	at mSearch.tool.ApplicationConfiguration.<init>(ApplicationConfiguration.java:65)
	at mSearch.tool.ApplicationConfiguration.<clinit>(ApplicationConfiguration.java:58)
	... 17 more
```

**Comment by derreisende77** [comment]
Don't use Wayland ;) obviously this problem is related to Java itself and your environment and not a big with the application. Therefore we are not the right address for it.

**Comment by erAck** [comment]
Well, the same environment works fine with earlier MediathekView releases (i.e. 13.0.6), so whatever change it introduced is causing this maybe could check available functionality.

**Comment by derreisende77** [comment]
Well 13.0.6 used Swing and 2D drawing only where 13.1+ use JavaFX as well and there java uses another renderer. But again this is not a problem with the app itself.
You may want to check [this link](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s)

But anyway we can´t help you with this problem. This is related to your system.

**Comment by shoeper** [comment]
@erAck from the link it looks like you've to install additional dependencies.

**Comment by shoeper** [comment]
Maybe `dnf install openjfx` is enough.

**Comment by erAck** [comment]
OpenJFX 8.0.152 is installed, see original posting, otherwise the trace involving javafx.* wouldn't be possible.. I'll upgrade to F28 anyway, maybe that'll fix things.
