### ISSUE TITLE
[Linux, Debian Buster/Sid, Java 8] MediathekView startet nicht mehr

### ISSUE THREAD

**Issue by x2k13** [mediathekview/MediathekView#377]
Nach einem Update von Java bzw. JavaFX scheint es seit einigen Tagen etwas zu geben, das MediathekView (Version 13.2.1) auf Debian Testing am starten hindert. Hier weitere Info:

```
./MediathekView.sh 

___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  


. Portable Mode: false
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mediathek.Main.setupPortableMode(Main.java:149)
	at mediathek.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

apt policy sagt:
```
openjdk-8-jre-headless:
  Installiert:           8u171-b11-2

openjfx:
  Installiert:           11+26-4
```
openjfx == JavaFX

Hat jemand von euch eine Idee, wie das zu fixen ist?

LG

**Comment by derreisende77** [comment]
Du hast ein Java 8 mit JavaFX für Java 11 installiert. Da ist es kein Wunder das es nicht geht.  Du musst openjfx für Java 8 haben.
Alternativ empfehlen wir Oracle Java 8 zu installieren. 

Von meinem iPhone gesendet

**Comment by Kasperx** [comment]
Unfortunately not a stable solution as you can read here...
https://github.com/mediathekview/MediathekView/issues/357
