### ISSUE TITLE
MediathekView 13.2.1: kontinuierliche NoSuchMethodError Exceptions unter Linux

### ISSUE THREAD

**Issue by frispete** [mediathekview/MediathekView#380]
Hi,
 wenn ich MediathekView.sh von der Konsole starte, sehe ich kontinuierliche NoSuchMethodError Exceptions unter Linux:
´´´
java.lang.NoSuchMethodError: sun.java2d.SurfaceData.getDefaultScale()I
        at javafx.embed.swing.JFXPanel.paintComponent(JFXPanel.java:693)
        at javax.swing.JComponent.paint(JComponent.java:1047)
        at javax.swing.JComponent.paintChildren(JComponent.java:880)
        at javax.swing.JComponent.paint(JComponent.java:1056)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5201)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
        at javax.swing.JComponent._paintImmediately(JComponent.java:5149)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4960)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
        at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
´´´
unabhängig davon, ob Metal oder GTK+ als GUI Theme gesetzt ist. Interessanterweise funktioniert das Programm trotzdem, nur halt mit Hintergrund-IO...

Es riecht ja nach der JVM (1.8.0), die da crasht, aber ich bemühe mich redlich, einen Build mit möglichst aktuellen Komponenten hinzubekommen, und zwar [hier](https://build.opensuse.org/project/monitor/home:frispete:java). Habe das Problem unter verschiedenen openSUSE Versionen reproduziert, nachdem ich gelernt habe, dass MediathekView nur richtig mit einer JVM läuft, die EC SSL unterstützt...

**Comment by derreisende77** [comment]
Ja irgendwas stimmt mit deinem Java nicht. Aber keine Ahnung was. Da scheinen Teile für die Grafik zu fehlen.
MV wird meines Wissens nach von einigen erfolgreich unter opensuse betrieben. Am besten Mal bei uns im Forum Fragen. Hier ist das eher der falsche Ort
