### ISSUE TITLE
Startet nicht unter Ubuntu 18.10

### ISSUE THREAD

**Issue by franktopel** [mediathekview/MediathekView#386]
Ausführen von `MediathekView.sh` in der bash gibt folgende Fehlermeldung aus;

```bash
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at mediathek.Main.setupPortableMode(Main.java:149)
	at mediathek.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 11 more
```

**Comment by KlausHans** [comment]
Hallo und sorry, dass ich das geschlossene Issue rauskramen muss. Ich habe exakt das selbe Problem auf Ubuntu 18.10. 
Ich habe die Anleitung von Ubuntuusers befolgt und u.a. sowohl openjdk-8-jre als auch openjfx installiert. Woran könnte es noch liegen?

Die Version aus der Paketverwaltung funktioniert übrigens auch nicht. :(

**Comment by mcs1998** [comment]
`Startparameter: -auto
. Startparameter: -noGUI
. Portable Mode: false
. Proxy Authentication: not configured
. java.awt.HeadlessException
. Programmstart: 28.12.2018 10:43:46
. maxMemory: 954 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Oracle Corporation
. VMname: OpenJDK 64-Bit Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-8u181-b13-2~deb9u1-b13
. Programmpfad: /usr/local/bin/MediathekView-13.2.1/
. Verzeichnis Einstellungen: /home/user/.mediathek3
. 
. 
. 
. Einstellungen laden: /home/user/.mediathek3/mediathek.xml
.  
.  =======================================
.  Systemparameter
.  -----------------
.  Download-Timeout [s]: 250
.  max. Download-Restart: 5
.  max. Download-Restart-Http: 10
.  Download weiterführen in [s]: 60
.  Download Fehlermeldung anzeigen [s]: 120
.  Downoadprogress anzeigen: true
Exception in thread "DummyFXApp Thread" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
.  User-Agent: Mozilla
.  =======================================
.  
. Liste Filme lesen von: /home/user/.mediathek3/filme.json
. initializeDatabase()
. initializeDatabase() done.
. Creating SQL indices
. Finished creating SQL indices
. Liste Filme gelesen am: 28.12.2018, 10:44
.   erstellt am: 28.12.2018, 09:16
.   Anzahl Filme: 268773
. Die Filmliste ist 87 Minuten alt
. aktuelle Filmliste verwenden
. ========== ========== ========== ========== ==========
`

Leider geht -auto nicht mehr in Ubuntu 18.10. ich bekomme immer eine no display fehlermeldung
Bin fuer jeden Vorschlag dankbar.
Liebe Gruesse
