### ISSUE TITLE
Mediathekview.exe macht gar nichts mit Java 11

### ISSUE THREAD

**Issue by rob-X1** [mediathekview/MediathekView#407]
Die aktuelle Version 13.2.1 funktionieren nicht korrekt wenn Java11 als primäre Java-JRE verwendet wird (PATH und JAVA_HOME zeigen auf Java 11). 
Java 8 habe ich auch installiert, das wird aber anscheinend ignoriert.

Versucht man MediathekView über die EXE-Dateien zu starten passiert einfach nichts. 

Startet man MediathekView über `java -jar MediathekView.jar` sieht man den Fehler:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at mediathek.Main.setupPortableMode(Main.java:149)
        at mediathek.Main.main(Main.java:158)
```
In Java 11 ist standardmäßig kein JavaFX mehr enthalten. Dieses muss man manuell installieren, was für normale Nutzer nicht so einfach ist. 

Auf der Webseite steht, das für MediathekView mindestens Java 8 benötigt wird, das es mit Java11 ohne JavaFX nicht geht findet man da nicht. 

Kurzfristig sollte der Fehler in `mediathek.Main.main()` abgefangen werden und ein entsprechende Fehlermeldung dem Nutzer angezeigt werden.

Langfristig sollte daher MediathekView umgestellt werden auf ein Release, bei dem die Java Runtime und alle Bibliotheken wie JavaFX mitgeliefert wird. Das ist die vorgesehene Methode für Java 11.

**Comment by derreisende77** [comment]
Und genau das alles ist schon im develop Branch drin. Java 11 jar mit JavaFX bundle. 
Auch die Release notes sagen eindeutig das es mit Java 9+ nicht funktioniert
