### ISSUE TITLE
MediathekView unter aktuelles Ubuntu nicht lauffähig

### ISSUE THREAD

**Issue by knmkuriq** [mediathekview/MediathekView#416]
Unter Ubuntu 18.04 LTS ist MediathekView nicht lauffähig.
Grund: OpenJDK 8 ist zwar installierbar und mit "sudo update-alternatives --config java" auch aktivierbar, bringt aber nichts, da man natürlich auch ein passendes OpenJFX braucht. Aber eben an dieses OpenJFX scheitert alles. Ich habe MediathekView gemäß offizielle Anleitung installiert:
https://mediathekview.de/anleitung/#installation-%C3%BCber-die-paketverwaltung

Hier das entspreche Paket in der Paketverwaltung: https://packages.ubuntu.com/de/bionic/mediathekview

MediathekView öffnet sich dann kurz und schließt sich.
Wenn man es in der Kommandozeile öffnet, dann steht da, dass es OpenJFX nicht finden könne.
Wenn es mit apt install openjfx installiert wird, dann wird entsprechend Version 11 installiert.
Paketquellen: https://packages.ubuntu.com/search?lang=de&arch=amd64&searchon=names&keywords=openjfx

Und nun haben wir das Problem. Ich kann so viel ich will auf openjdk 8 umstellen. Das wird aber nie funktionieren, denn die Fehlermeldung mit fehlendes openjfx wird immer erscheinen, da ich ein openjfx8 gar nicht installieren kann. Ich müsste ein Ubuntu aus 2016 nehmen (16.04 LTS) um MediathekView ausführen zu können. Dieses hat noch openjfx8. Das kommt aber nicht in Frage, da dafür in kürze der Support eingestellt wird und damit meine Hardware nicht lauffähig ist(viel zu alte Software in 16.04).

Ich habe auch die latest-datei von mediathekview (13.2.1) für linux von der webseite geladen, entpackt und die mediathekview.sh ausgeführt.
Auch dort kann kein openjfx gefunden werden.

Ausgabe bei 13.2.1 mit installiertes und systemweit eingestelltes openjdk8 aber natürlich openjfx11, da es kein anderes openjfx zum installieren gibt.

. Portable Mode: false
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at mediathek.Main.setupPortableMode(Main.java:149)
        at mediathek.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

**Comment by alex1702** [comment]
Ich hab mir mal die Arbeit gemacht das [AppImage](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage) lokal zu erzeugen. Ihr Könnt unter Ubuntu 18.04, darauf aufbauende Distributionen oder neueren Ubuntu Version diese Version nutzen. Sie bringt Java 8 schon mit.

Download [hier](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage)

Dieses muss nur ausführbar gemacht werden und kann dann aufgerufen werden.

**Comment by probonopd** [comment]
Vielen Dank für das AppImage, crasht bei mir leider im Test:
https://github.com/AppImage/appimage.github.io/pull/1524

**Comment by alex1702** [comment]
> Vielen Dank für das AppImage, crasht bei mir leider im Test:
> [AppImage/appimage.github.io#1524](https://github.com/AppImage/appimage.github.io/pull/1524)

Beim Ausführen von meinem gebauten oder von dem in deinem referenzierten?
Und welche Umgebung?

**Comment by Eric-Sommer** [comment]
> Ich hab mir mal die Arbeit gemacht das [AppImage](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage) lokal zu erzeugen. Ihr Könnt unter Ubuntu 18.04, darauf aufbauende Distributionen oder neueren Ubuntu Version diese Version nutzen. Sie bringt Java 8 schon mit.
> 
> Download [hier](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage)
> 
> Dieses muss nur ausführbar gemacht werden und kann dann aufgerufen werden.

Danke, bei mir wurde das Problem dadurch gelöst (Linux Mint 19.1)

**Comment by CarstenMeyer** [comment]
Nutze das angebene AppImage von @alex1702 jetzt auch unter Ubuntu 18.04 LTS mit Java-Bibliotheken im Auslieferungszustand ohne Probleme. Danke!

Sollte das AppImage vielleicht auf der Download-Seite (https://mediathekview.de/download/) verlinkt werden?

**Comment by alex1702** [comment]
> Sollte das AppImage vielleicht auf der Download-Seite (https://mediathekview.de/download/) verlinkt werden?

Kommt noch. Im Moment wird es ja auch noch nicht automatisch gebaut.
