### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by boldt** [mediathekview/MediathekView#420]
Ich habe:

* Ubuntu 18.04
* die neuste `MediathekView-latest.tar.gz` heruntergeladen und nach `/opt/MediathekView/` verschoben
* Oracle Java8 unter `/opt` installiert

Wenn ich das nun starte bekomme ich den folgenden Fehler:

```
/opt/java/jre1.8.0_212/bin/java -Xms512M -Xmx512M -jar /opt/MediathekView/MediathekView.jar





___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  


. Portable Mode: false
. Proxy Authentication: not configured
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at mediathek.MediathekGui.<init>(MediathekGui.java:1006)
	at mediathek.Main.getPlatformWindow(Main.java:297)
	at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.QuantumToolkit.resumeTimer(QuantumToolkit.java:511)
	at com.sun.javafx.tk.quantum.QuantumToolkit.access$000(QuantumToolkit.java:135)
	at com.sun.javafx.tk.quantum.QuantumToolkit$PulseTask.set(QuantumToolkit.java:202)
	at com.sun.javafx.tk.quantum.QuantumToolkit.setAnimationRunnable(QuantumToolkit.java:865)
	at com.sun.javafx.tk.quantum.MasterTimer.postUpdateAnimationRunnable(MasterTimer.java:105)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.updateAnimationRunnable(AbstractMasterTimer.java:324)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.access$100(AbstractMasterTimer.java:253)
	at com.sun.scenario.animation.AbstractMasterTimer.addPulseReceiver(AbstractMasterTimer.java:176)
	at javafx.animation.Animation.addPulseReceiver(Animation.java:148)
	at javafx.animation.Animation.startReceiver(Animation.java:154)
	at javafx.animation.Animation.play(Animation.java:913)
	at javafx.animation.Animation.playFromStart(Animation.java:961)
	at mSearch.tool.ApplicationConfiguration$EvtListener.onEvent(ApplicationConfiguration.java:96)
	at mSearch.tool.ApplicationConfiguration$EvtListener.onEvent(ApplicationConfiguration.java:79)
	at org.apache.commons.configuration2.event.EventListenerList.callListener(EventListenerList.java:297)
	at org.apache.commons.configuration2.event.EventListenerList.access$200(EventListenerList.java:56)
	at org.apache.commons.configuration2.event.EventListenerList$EventListenerIterator.invokeNextListenerUnchecked(EventListenerList.java:421)
	at org.apache.commons.configuration2.event.EventListenerList$EventListenerIterator.invokeNext(EventListenerList.java:361)
	at org.apache.commons.configuration2.event.BaseEventSource.fireEvent(BaseEventSource.java:235)
	at org.apache.commons.configuration2.AbstractConfiguration.setProperty(AbstractConfiguration.java:793)
	at mSearch.tool.ApplicationConfiguration.createDefaultConfigSettings(ApplicationConfiguration.java:135)
	at mSearch.tool.ApplicationConfiguration.loadOrCreateConfiguration(ApplicationConfiguration.java:122)
	at mSearch.tool.ApplicationConfiguration.<init>(ApplicationConfiguration.java:68)
	at mSearch.tool.ApplicationConfiguration.<clinit>(ApplicationConfiguration.java:58)
	... 17 more
```

Die NPE schaut nicht gut aus. Was kann ich machen?

**Comment by derreisende77** [comment]
`/opt/java/jre1.8.0_212/bin/java -Xmx1G -jar /opt/MediathekView/MediathekView.jar
`
sollte erst mal der Befehl lauten. Mit deiner Kombination darf das Programm maximal 512MB nutzen was von Haus aus so nicht unterstützt wird. Das Programm benötigt zum vernünftigen laufen 1GB RAM. 
Ansonsten deutet der Fehler auf ein Problem mit JavaFX hin. Ich hoffe das ist mit dem Speicher Geschichte ansonsten kann ich da erst mal nicht viel dagegen tun.

**Comment by derreisende77** [comment]
Evtl hilft es noch `export JAVA_HOME=/opt/java/jre1.8.0_212` vorher mal auszuführen. 
Wenn das nicht hilft, fällt mir als letztes nur noch ein das JDK zu installieren.
