### ISSUE TITLE
[Mac] Programm bleibt beim Start hängen

### ISSUE THREAD

**Issue by OgreTransporter** [mediathekview/MediathekView#421]
Das Programm bleibt beim Laden hägen. Um den Fehler reproduzieren zu können habe ich das Programm via Terminal gestartet:

```
java -jar MediathekView.jar
. Portable Mode: false
. Proxy Authentication: not configured
. Programmstart: 02.06.2019 21:06:29
. maxMemory: 1908 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Oracle Corporation
. VMname: Java HotSpot(TM) 64-Bit Server VM
. Version: 1.8.0_60
. Runtimeversion: 1.8.0_60-b27
. Programmpfad: /Applications/MediathekView.app/Contents/java/app/
. Verzeichnis Einstellungen: /Users/transporter/.mediathek3
.
.
.
. ========== ========== ========== ========== ==========
. DURATION 0: Start [433,00 ms]
. Klasse: MediathekGuiMac.<init>
. ========== ========== ========== ========== ==========
.
. =======================================
. Systemparameter
. -----------------
. Download-Timeout [s]: 250
. max. Download-Restart: 5
. max. Download-Restart-Http: 10
. Download weiterführen in [s]: 60
. Download Fehlermeldung anzeigen [s]: 120
. Downoadprogress anzeigen: true
. User-Agent: MediathekView
. =======================================
.
. Konfig wurde gelesen!
. ========== ========== ========== ========== ==========
. DURATION 1: Start Gui [117,00 ms]
. Klasse: MediathekGuiMac.<init>
. ========== ========== ========== ========== ==========
. initializeDatabase()
org.h2.jdbc.JdbcSQLException: Datei fehlerhaft beim Lesen des Datensatzes: null. Mögliche Lösung: Recovery Werkzeug verwenden
File corrupted while reading record: null. Possible solution: use the recovery tool [90030-197]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
at org.h2.message.DbException.get(DbException.java:168)
at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:196)
at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
at org.h2.engine.Database.getPageStore(Database.java:2538)
at org.h2.engine.Database.open(Database.java:709)
at org.h2.engine.Database.openDatabase(Database.java:286)
at org.h2.engine.Database.<init>(Database.java:280)
at org.h2.engine.Engine.openSession(Engine.java:66)
at org.h2.engine.Engine.openSession(Engine.java:179)
at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
at org.h2.engine.Engine.createSession(Engine.java:140)
at org.h2.engine.Engine.createSession(Engine.java:28)
at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
at org.h2.Driver.connect(Driver.java:69)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:208)
at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:92)
at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:291)
at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:883)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:436)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:365)
at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
at mSearch.daten.PooledDatabaseConnection.getConnection(PooledDatabaseConnection.java:56)
at mSearch.daten.DatenFilm$Database.initializeDatabase(DatenFilm.java:637)
at mSearch.daten.DatenFilm$Database.access$000(DatenFilm.java:607)
at mSearch.daten.DatenFilm.<clinit>(DatenFilm.java:107)
at mediathek.tool.table.MVFilmTable.setupTableType(MVFilmTable.java:15)
at mediathek.tool.table.MVTable.<init>(MVTable.java:68)
at mediathek.tool.table.MVFilmTable.<init>(MVFilmTable.java:9)
at mediathek.gui.GuiFilme.<init>(GuiFilme.java:92)
at mediathek.MediathekGui.initTabs(MediathekGui.java:555)
at mediathek.MediathekGui.init(MediathekGui.java:474)
at mediathek.MediathekGui.<init>(MediathekGui.java:207)
at mediathek.mac.MediathekGuiMac.<init>(MediathekGuiMac.java:29)
at mediathek.Main.getPlatformWindow(Main.java:290)
at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 8336, expected page length 4..1024, got 1702064242 [1.4.197/6]
at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
at org.h2.mvstore.Page.read(Page.java:652)
at org.h2.mvstore.Page.read(Page.java:186)
at org.h2.mvstore.MVStore.readPage(MVStore.java:1936)
at org.h2.mvstore.MVMap.readPage(MVMap.java:698)
at org.h2.mvstore.Page.getChildPage(Page.java:208)
at org.h2.mvstore.Cursor.fetchNext(Cursor.java:150)
at org.h2.mvstore.Cursor.next(Cursor.java:50)
at org.h2.mvstore.MVStore.loadChunkMeta(MVStore.java:684)
at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:664)
at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
... 50 more
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
at mediathek.tool.table.MVFilmTable.setupTableType(MVFilmTable.java:15)
at mediathek.tool.table.MVTable.<init>(MVTable.java:68)
at mediathek.tool.table.MVFilmTable.<init>(MVFilmTable.java:9)
at mediathek.gui.GuiFilme.<init>(GuiFilme.java:92)
at mediathek.MediathekGui.initTabs(MediathekGui.java:555)
at mediathek.MediathekGui.init(MediathekGui.java:474)
at mediathek.MediathekGui.<init>(MediathekGui.java:207)
at mediathek.mac.MediathekGuiMac.<init>(MediathekGuiMac.java:29)
at mediathek.Main.getPlatformWindow(Main.java:290)
at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
at mSearch.daten.DatenFilm$Database.initializeDatabase(DatenFilm.java:638)
at mSearch.daten.DatenFilm$Database.access$000(DatenFilm.java:607)
at mSearch.daten.DatenFilm.<clinit>(DatenFilm.java:107)
... 24 more
```
Ich habe mehrere Dinge ausprobiert, bekomme aber immer die gleiche Fehlermeldung:
1. Löschen des Verzeichnis `.mediathek3`
2. Kopieren einer funktionierenden Datenbank von Windows in `.mediathek3`
3. Programm neu downloaden und installieren
4. Java-Update

Irgendeine Idee, wie ich das Programm zum laufen bekomme?

**Comment by styroll** [comment]
> @OgreTransporter sagte:  initializeDatabase()
org.h2.jdbc.JdbcSQLException: Datei fehlerhaft beim Lesen des Datensatzes: null. Mögliche Lösung: Recovery Werkzeug verwenden
File corrupted while reading record: null. Possible solution: use the recovery tool

Lösch mal die Datenbank in: ~/Library/Caches/MediathekView/

**Comment by OgreTransporter** [comment]
Perfekt, funktioniert wieder! Vielen Dank!
