### ISSUE TITLE
13.3.0: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by ghost** [mediathekview/MediathekView#442]
Installiert habe ich Java 8 x64 Update 221 auf Windows 10 Pro. Java 11 ist gewünscht... diese Version gibt es aber nicht. Geführt wird zum Downloadlink der von mir bereits installierten Version.

**Comment by derreisende77** [comment]
https://forum.mediathekview.de/topic/2653/aufruf-mv-installer/2

**Comment by chrisdane** [comment]
Hey, I have the same error on arch linux 5.18:
```
mediathekview 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: mediathek/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

```bash
java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (build 25.332-b09, mixed mode)
```

```bash
pacman -Qi mediathekview
Name            : mediathekview
Version         : 13.8.1-3
Description     : Access the Mediathek of many German TV stations
Architecture    : any
URL             : https://github.com/mediathekview/mediathekview
Licenses        : GPL3
Groups          : None
Provides        : mediathek
Depends On      : bash  hicolor-icon-theme  java-runtime
Optional Deps   : libnotify: to use desktop notifications [installed]
                  mplayer: for recording streams
                  vlc: for stream playback [installed]
Required By     : None
Optional For    : None
Conflicts With  : mediathek
Replaces        : mediathek
Installed Size  : 77.35 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Sun 19 Dec 2021 07:40:04 PM CET
Install Date    : Thu 23 Dec 2021 06:24:27 PM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

Thanks a lot for help,
Chris

**Comment by derreisende77** [comment]
You need java 17 or later to run 13.8. java 8 cannot run the application.

**Comment by chrisdane** [comment]
I have
```
pacman -Qi jdk-openjdk 
Name            : jdk-openjdk
Version         : 18.0.1.1.u2-1
```
and mediathekview worked for a long time. I did not change anything. 

Could you point me to the correct java for arch linux?

Thanks a lot!
