### ISSUE TITLE
Nullpointer on startup

### ISSUE THREAD

**Issue by Kai-W** [mediathekview/MediathekView#453]
"C:\Program Files\Java\jre1.8.0_221\bin\java" -Xmx1G -jar ./MediathekView.jar

. Portable Mode: false
. Proxy Authentication: not configured
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at mediathek.MediathekGui.<init>(MediathekGui.java:1006)
        at mediathek.windows.MediathekGuiWindows.<init>(MediathekGuiWindows.java:9)
        at mediathek.Main.getPlatformWindow(Main.java:292)
        at mediathek.Main.lambda$startGuiMode$0(Main.java:282)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.resumeTimer(QuantumToolkit.java:511)
        at com.sun.javafx.tk.quantum.QuantumToolkit.access$000(QuantumToolkit.java:135)
        at com.sun.javafx.tk.quantum.QuantumToolkit$PulseTask.set(QuantumToolkit.java:202)
        at com.sun.javafx.tk.quantum.QuantumToolkit.setAnimationRunnable(QuantumToolkit.java:865)
        at com.sun.javafx.tk.quantum.MasterTimer.postUpdateAnimationRunnable(MasterTimer.java:105)
        at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.updateAnimationRunnable(AbstractMasterTimer.java:324)
        at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.access$100(AbstractMasterTimer.java:253)
        at com.sun.scenario.animation.AbstractMasterTimer.addPulseReceiver(AbstractMasterTimer.java:176)
        at javafx.animation.Animation.addPulseReceiver(Animation.java:148)
        at javafx.animation.Animation.startReceiver(Animation.java:154)
        at javafx.animation.Animation.play(Animation.java:913)
        at javafx.animation.Animation.playFromStart(Animation.java:961)
        at mSearch.tool.ApplicationConfiguration$EvtListener.onEvent(ApplicationConfiguration.java:96)
        at mSearch.tool.ApplicationConfiguration$EvtListener.onEvent(ApplicationConfiguration.java:79)
        at org.apache.commons.configuration2.event.EventListenerList.callListener(EventListenerList.java:297)
        at org.apache.commons.configuration2.event.EventListenerList.access$200(EventListenerList.java:56)
        at org.apache.commons.configuration2.event.EventListenerList$EventListenerIterator.invokeNextListenerUnchecked(EventListenerList.java:421)
        at org.apache.commons.configuration2.event.EventListenerList$EventListenerIterator.invokeNext(EventListenerList.java:361)
        at org.apache.commons.configuration2.event.BaseEventSource.fireEvent(BaseEventSource.java:235)
        at org.apache.commons.configuration2.AbstractConfiguration.setProperty(AbstractConfiguration.java:793)
        at mSearch.tool.ApplicationConfiguration.createDefaultConfigSettings(ApplicationConfiguration.java:135)
        at mSearch.tool.ApplicationConfiguration.loadOrCreateConfiguration(ApplicationConfiguration.java:122)
        at mSearch.tool.ApplicationConfiguration.<init>(ApplicationConfiguration.java:68)
        at mSearch.tool.ApplicationConfiguration.<clinit>(ApplicationConfiguration.java:58)
        ... 18 more

**Comment by derreisende77** [comment]
There have been issues with Java update 221. Maybe try update 211 or upgrade to latest MV version.  This requires Java 11 minimum.
