### ISSUE TITLE
java.lang.UnsupportedOperationException: FreeBSD is not supported

### ISSUE THREAD

**Issue by bsdlme** [mediathekview/MediathekView#473]
Seit Version 13.3.0 funktioniert MediathekView nicht mehr unter FreeBSD:

```
java.lang.UnsupportedOperationException: FreeBSD is not supported
	at com.sun.javafx.tk.Toolkit.getDefaultToolkit(Toolkit.java:195)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:229)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:241)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:257)
	at mediathek.Main.initializeJavaFX(Main.java:302)
	at mediathek.Main.main(Main.java:272)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.mediathek.Main_MediathekView.main(Unknown Source)
```

Heruntergeladen habe ich das .tar.gz für Linux und installiert ist OpenJDK 12 auf FreeBSD 12.0.

Seit MediathekView Version 2.2.1 existiert schon ein Port für FreeBSD, den ich jetzt leider nicht mehr aktualisieren kann.

**Comment by alex1702** [comment]
Wenn ich das richtig sehe kommt das durch install4j...ärgerlich...

**Comment by bsdlme** [comment]
Danke, ich schaue mir das am Montag mal weiter an. Die mitgelieferte Java-Version wird leider nicht funktionieren, weil das ja eine Linux-Binary ist. Beim AppImage wird das auch so sein, oder?

**Comment by derreisende77** [comment]
Das ganze hat nichts mit install4j oder jdk zu tun. Die Initialisierung von JavaFX schlägt wegen fehlender native bsd libraries fehl. Alle MV Versionen sind nur Linux Mac oder Windows von daher kann es nicht funktionieren. 
Auch ein selbst bauen für bsd wird dir nicht helfen da openjfx nur win mac und Linux offiziell unterstützt. Du könntest versuchen OpenJFX für bsd selbst zu compilen aber ich gehe davon aus das es nicht leicht sein wird. Irgendwo soll es angeblich einen inoffiziellen bsd Port geben aber den konnte ich nicht finden. 

So gesehen bleibt aus meiner Sicht nur die Nutzung einer VM oder Ähnlichem um eine Linux App unter bsd auszuführen. Alle anderen Versuche werden wohl erfolglos bleiben.
