### ISSUE TITLE
Mediathekview kann Senderliste nicht aktualisieren

### ISSUE THREAD

**Issue by joker-mik** [mediathekview/MediathekView#474]
Version 0.6.2 auf dem FireTV Stick 4k unter Kodi 18.4 verursacht folgenden Fehler

2019-11-14 22:58:39.705 T:32020  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
2019-11-14 22:58:40.583 T:32017   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                                from resources.lib.updater import MediathekViewUpdater
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 24, in <module>
                                                import ijson
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 28, in <module>
                                                backend = _default_backend()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 24, in _default_backend
                                                return importlib.import_module('ijson.backends.' + backend)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/yajl2.py", line 12, in <module>
                                                yajl = backends.find_yajl_ctypes(2)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/__init__.py", line 34, in find_yajl_ctypes
                                                so_name = util.find_library('yajl')
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/ctypes/util.py", line 274, in find_library
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/ctypes/util.py", line 99, in _findLib_gcc
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/tempfile.py", line 463, in NamedTemporaryFile
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/tempfile.py", line 275, in gettempdir
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            -->End of Python script error report<--

**Comment by alex1702** [comment]
Falsches Repo. Du meinst [plugin.video.mediathekview](https://github.com/mediathekview/plugin.video.mediathekview) und es sollte das gleiche Problem wie in [#134](https://github.com/mediathekview/plugin.video.mediathekview/issues/134) sein.

**Comment by joker-mik** [comment]
Danke für den Link des richtigen Repo
Sorry für die Falschmeldung.
