### ISSUE TITLE
swamps logs with gigabytes of error-messages

### ISSUE THREAD

**Issue by Seegras** [mediathekview/MediathekView#662]
It fills databasemediathekview.trace.db and mediathekview.log with some gigabytes of errors for only one run. Basically, it's now impossible to start. 

`2022-06-09 18:02:21 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Schema "MEDIATHEKVIEW" not found; SQL statement:
INSERT INTO mediathekview.film VALUES (?) [90079-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getSchema(Parser.java:1052)
	at org.h2.command.Parser.getSchema(Parser.java:1058)
	at org.h2.command.Parser.readTableOrView(Parser.java:8311)
	at org.h2.command.Parser.readTableOrView(Parser.java:8306)
	at org.h2.command.Parser.parseInsert(Parser.java:1641)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:696)
	at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:696)
	at mSearch.daten.DatenFilm.writeFilmNumberToDatabase(DatenFilm.java:171)
	at mSearch.daten.DatenFilm.<init>(DatenFilm.java:164)
	at mSearch.filmlisten.reader.FilmListReader.readData(FilmListReader.java:262)
	at mSearch.filmlisten.reader.FilmListReader.processFromWeb(FilmListReader.java:407)
	at mSearch.filmlisten.reader.FilmListReader.readFilmListe(FilmListReader.java:318)
	at mediathek.filmlisten.ImportFilmliste.urlLaden(ImportFilmliste.java:95)
	at mediathek.filmlisten.FilmeImportierenAutoThread.searchFullList(FilmeImportierenAutoThread.java:82)
	at mediathek.filmlisten.FilmeImportierenAutoThread.run(FilmeImportierenAutoThread.java:40)`

My guess is, it's somehow using a deprecated feature of java or some library.

**Comment by derreisende77** [comment]
You would have to delete the database in the `.mediathek3` directory as it got somehow corrupted. It is not a problem with some library or deprecated feature.
Anyway 13.2.1 is an outdated old version and you should use a newer one.
