### ISSUE TITLE
java.lang.Exception: Unknown TTML file version

### ISSUE THREAD

**Issue by 0x6d61726b** [mediathekview/MediathekView#663]
Hello all,

I have problems downloading some (not all) episodes from ORF with latest MediathekView v13.8.1 which is aborted with a "fehlerhaft" error message and the log file states a `java.lang.Exception: Unknown TTML file version`.

The file "Soko Kitzbühel-Betrogen-0437229427.ttml" however is present in a reasonable size (42755 bytes) and from a first glance seems to be complete (at least it ends with `</div></body></tt>`).

Here is the partial log file information:
```
INFO  2022-06-26 10:00:06,686  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.StarterClass (StarterClass.java:117) - [Download starten, Programmset: Speichern, Ziel: C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4, URL: https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8, Startzeit: 2022-06-26T10:00:06.639761, Programmaufruf: bin\ffmpeg.exe -i https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8 -c copy -bsf:a aac_adtstoasc "C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4", Programmaufruf[]: bin\ffmpeg.exe<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>"C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4"]
INFO  2022-06-26 10:00:06,689  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.RuntimeExec (RuntimeExec.java:91) - =====================
INFO  2022-06-26 10:00:06,689  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.RuntimeExec (RuntimeExec.java:92) - Starte Array: 
INFO  2022-06-26 10:00:06,690  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.RuntimeExec (RuntimeExec.java:93) -  -> bin\ffmpeg.exe<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>"C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4"
INFO  2022-06-26 10:00:06,690  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.RuntimeExec (RuntimeExec.java:94) - =====================
INFO  2022-06-26 10:00:06,982  [ForkJoinPool.commonPool-worker-1] tool.MVSubtitle (MVSubtitle.java:55) - Untertitel https://api-tvthek.orf.at/assets/subtitles/0138/25/146996ff6b869ad949c4ab40c9bad11ac9dfc6c4.ttml schreiben nach C:\SokoKitzbuehel
INFO  2022-06-26 10:00:07,078  [ForkJoinPool.commonPool-worker-1] tool.MVSubtitle (MVSubtitle.java:40) - Untertitel-Datei wurde geschrieben
ERROR 2022-06-26 10:00:07,139  [ForkJoinPool.commonPool-worker-1] tool.TimedTextMarkupLanguageParser (TimedTextMarkupLanguageParser.java:216) - File: C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.ttml
java.lang.Exception: Unknown TTML file version
	at mediathek.tool.TimedTextMarkupLanguageParser.parse(TimedTextMarkupLanguageParser.java:206) ~[MediathekView.jar:?]
	at mediathek.tool.MVSubtitle.convertSubtitle(MVSubtitle.java:85) ~[MediathekView.jar:?]
	at mediathek.tool.MVSubtitle.writeSubtitle(MVSubtitle.java:70) ~[MediathekView.jar:?]
	at mediathek.controller.starter.ExternalProgramDownload.lambda$startSubtitleFileDownload$2(ExternalProgramDownload.java:210) ~[MediathekView.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
INFO  2022-06-26 10:00:07,304  [ForkJoinPool.commonPool-worker-1] tool.MVSubtitle (MVSubtitle.java:90) - Untertitel-Datei wurde konvertiert.
INFO  2022-06-26 10:00:08,828  [EXTERNAL PROGRAM DL THREAD: Betrogen] starter.StarterClass (StarterClass.java:169) - [Download ist fertig und war fehlerhaft, Programmset: Speichern, Ziel: C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4, Startzeit: 2022-06-26T10:00:06.639761, Endzeit: 2022-06-26T10:00:08.8268871, Restarts: 0, Dauer: 2 s, URL: https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8, Programmaufruf: bin\ffmpeg.exe -i https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8 -c copy -bsf:a aac_adtstoasc "C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4", Programmaufruf[]: bin\ffmpeg.exe<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide/2022-06-24_1740_sd_06_Soko-Kitzbuehel_____14140201__o__1995086541__s15188233_3__ORF3HD_17422618P_18254814P_Q8C.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>"C:\SokoKitzbuehel\Soko Kitzbühel-Betrogen-0437229427.mp4"]
```

Information about used MediathekView:
```
INFO  2022-06-26 09:57:56,718  [main] mediathek.Main (Main.java:297) - Configuring for non-portable mode
INFO  2022-06-26 09:57:58,542  [main] mediathek.Main (Main.java:243) - Programmstart: 2022-06-26T09:57:58.5359309
INFO  2022-06-26 09:57:58,830  [main] mediathek.Main (Main.java:244) - Version: 13.8.1
INFO  2022-06-26 09:57:58,836  [main] mediathek.Main (Main.java:246) - === Java Information ===
INFO  2022-06-26 09:57:58,856  [main] mediathek.Main (Main.java:248) - Vendor: Eclipse Adoptium
INFO  2022-06-26 09:57:58,858  [main] mediathek.Main (Main.java:249) - VMname: OpenJDK 64-Bit Server VM
INFO  2022-06-26 09:57:58,859  [main] mediathek.Main (Main.java:250) - Version: 17.0.1
INFO  2022-06-26 09:57:58,860  [main] mediathek.Main (Main.java:251) - Runtime Version: 17.0.1+12
INFO  2022-06-26 09:57:58,862  [main] mediathek.Main (Main.java:253) - Maximum Memory: 8146 MB
INFO  2022-06-26 09:57:58,863  [main] mediathek.Main (Main.java:255) - Operating System: Windows 10
INFO  2022-06-26 09:57:58,866  [main] mediathek.Main (Main.java:256) - OS Version: 10.0
INFO  2022-06-26 09:57:58,867  [main] mediathek.Main (Main.java:257) - OS Arch: amd64
```

**Comment by derreisende77** [comment]
Yes it seems the TTML format has changed here and the parser fails as there is information missing from ORF.

**Comment by styroll** [comment]
>@derreisende77 sagte: Those subtitles are HTML and cannot be parsed with MV.

Wie muss man das verstehen? Wenn ich für den obigen ORF-Film "Soko Kitzbühel: Betrogen (15/18)" den Untertitel runterladen lasse, konvertiert MV die [TTML-Datei](https://api-tvthek.orf.at/assets/subtitles/0195/89/950d7c98ee2bafc6caf4eeac7f3a96e764e6e64a.ttml) sehr wohl ins SRT- und neu ins ASS-Format – mit folgendem Resultat:

- VLC: Okay mit ASS-Track, nicht jedoch mit SRT- und TTML-Track.
- IINA (ein MPV-Derivat): Okay mit ASS, SRT, nicht jedoch TTML.

Wenn ich eine andere ORF-Sendung oder eine ARD-Sendung nehme:

- VLC: Okay mit ASS und TTML, nicht jedoch mit SRT
- IINA: Okay mit ASS, SRT, nicht jedoch TTML.

Meine Interpretation aus dem bescheidenen Datensatz ist:

- Die TTML-Datei von einzelnen kann fehlerhaft sein, was auf einigen OS- oder MV-Versionen zur Meldung "fehlerhaft" führen kann, was ich aber auf meinem System nie verifizieren konnte ([2. Beispiel)](https://forum.mediathekview.de/post/38630).
- Die durch MV realisierte Konvertierung einer solch fehlerhaften TTML-Datei funktioniert trotzdem (ASS, SRT), nur die originale TTML-Datei kann VLC nicht abspielen (bis dahin habe ich gar nicht gewusst, dass VLC das kann).
- VLC kann so erzeugte SRT-Subs zumindest bei mir (macOS, VLC 3.0.21, arm64) nicht abspielen.

**Comment by derreisende77** [comment]
Da habe ich ein anderes issue vermischt. Die Exception hat nichts mit den o.g. Downloadproblemen des ORF zu tun. Sie kommt daher da die TTML Datei ein XML *Flash* Format ist und der erste Parser der darauf angewendet wird kann nur EBU Format lesen. Daher wird die Exception geworfen und der zweite Flash parser erzeugt dann erfolgreich die SRT und ASS Daten. In 14.4 wird die Exception unterdrückt und einfach nur eine Warnmeldung ins Log geschrieben.

**Comment by styroll** [comment]
>@derreisende77 sagte: Daher wird die Exception geworfen und der zweite Flash parser erzeugt dann erfolgreich die SRT und ASS Daten

Alles klar, danke für die Erläuterungen.
