### ISSUE TITLE
macOS: MV 13.9.0 schließt sich sofort nach Start wieder

### ISSUE THREAD

**Issue by workflowsguy** [mediathekview/MediathekView#665]
Upgrade von funktionierender Version 13.8.1. auf 13.9.0:

MV beendet sich nach Aufruf jedes Mal sofort.

Nach dem Umbenennen der bisherigen .mediathek3 findet sich im neu angelegten Verzeichnis in der Datei `mediathekview.log` folgendes:

```
INFO  2022-07-13 17:05:56,654  [main] mediathek.Main (Main.java:249) - Configuring for non-portable mode
ERROR 2022-07-13 17:05:58,854  [main] mediathek.Main (Main.java:355) - Command line parse error:
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278) ~[MediathekView.jar:?]
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291) ~[MediathekView.jar:?]
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163) ~[MediathekView.jar:?]
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:242) ~[MediathekView.jar:?]
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:258) ~[MediathekView.jar:?]
	at mediathek.Main.initializeJavaFX(Main.java:436) ~[MediathekView.jar:?]
	at mediathek.Main.main(Main.java:333) ~[MediathekView.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84) ~[i4jruntime.jar:?]
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52) ~[i4jruntime.jar:?]
```

macOS: 10.13.6 (Intel)

**Comment by derreisende77** [comment]
Fehler ist bekannt, die Binaries sind beschädigt. Es wird daran gearbeitet ein 13.9.1 Release zu veröffentlichen. Bis dahin ist [in diesem Thread](https://forum.mediathekview.de/topic/4817/13-9-0-mediathekview-startet-nicht-auf-macos-monterey/8) ein Link zu einer vorab veröffentlichten DMG als Workaround drin. Diese wird auch später auf der Homepage veröffentlicht werden.
