### ISSUE TITLE
ÖRF downloads fail with "Download ist fertig und war fehlerhaft"

### ISSUE THREAD

**Issue by Ottaviocr** [mediathekview/MediathekView#701]
For the last two weeks I was unable to download ZIB, for example:
https://tvthek.orf.at/profile/ZIB-2/1211/ZIB-2/14182825

I have changed ffmped and vlc user agents as per forum.

Host is Linux Debian Bullseye:

Log follows:

```
$ MediathekView 2>&1
. Configuring for non-portable mode
Jun 17, 2023 4:04:04 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @209da20d'
. Programmstart: 2023-06-17T16:04:04.551490691
. Version: 13.9.1
. === Java Information ===
. Vendor: Eclipse Adoptium
. VMname: OpenJDK 64-Bit Server VM
. Version: 17.0.2
. Runtime Version: 17.0.2+8
. Maximum Memory: 3917 MB
. Operating System: Linux
. OS Version: 6.0.0-0.deb11.6-amd64
. OS Arch: amd64
. OS Dark Mode detection not supported
. OS Available Processors: 4
. Verzeichnis Einstellungen: /home/oc/.mediathek3
. Konfig wurde gelesen!
. No custom font size found.

(java:28698): Gtk-CRITICAL **: 16:04:09.554: gtk_window_resize: assertion 'height > 0' failed
. Liste Filme gelesen am: 17.06.2023, 16:04
.   erstellt am: 17.06.2023, 14:28
.   Anzahl Filme: 611452
. Filme in Downloads eintragen
. -------------------------------------------------------
. Einstellungen sichern
. Einstellungen wurden gesichert
. -------------------------------------------------------
. MVHttpClient: Proxy not configured
. 
. Alte Liste erstellt am: 17.06.2023, 14:28
.   Anzahl Filme: 611452
.   Anzahl Neue: 6745
. Filmliste laden (Netzwerk)
. Liste Filme gelesen am: 17.06.2023, 16:04
.   erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 3641
. Liste Diff gelesen am: 17.06.2023, 16:04
.   Liste Diff erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 3641
. 
. Jetzige Liste erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 613200
.   Anzahl Neue:  1740
. 
. Filme in Downloads eintragen
. Filme schreiben (613200 Filme) :
.    --> Start Schreiben nach: /home/oc/.mediathek3/filme.json
.    --> geschrieben!
. 
. Alte Liste erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 613200
.   Anzahl Neue: 1740
. Filmliste laden von: 
. Liste Filme gelesen am: 17.06.2023, 16:07
.   erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 611670
. Liste Diff gelesen am: 17.06.2023, 16:07
.   Liste Diff erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 611670
. 
. Jetzige Liste erstellt am: 17.06.2023, 15:27
.   Anzahl Filme: 613207
.   Anzahl Neue:  0
. 
. Filme schreiben (613207 Filme) :
.    --> Start Schreiben nach: /home/oc/.mediathek3/filme.json
. Filme in Downloads eintragen
.    --> geschrieben!
. [Download starten, Programmset: Linux Speichern, Ziel: /home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4, URL: https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8, Startzeit: 2023-06-17T16:08:17.979265899, Programmaufruf: /home/oc/opt/bin/ffmpeg -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" -i https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8 -c copy -bsf:a aac_adtstoasc /home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4, Programmaufruf[]: /home/oc/opt/bin/ffmpeg<>-user_agent<>"Mozilla/5.0<>(Windows<>NT<>10.0;<>Win64;<>x64;<>rv:109.0)<>Gecko/20100101<>Firefox/109.0"<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>/home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4]
. =====================
. Starte Array: 
.  -> /home/oc/opt/bin/ffmpeg<>-user_agent<>"Mozilla/5.0<>(Windows<>NT<>10.0;<>Win64;<>x64;<>rv:109.0)<>Gecko/20100101<>Firefox/109.0"<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>/home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4
. =====================
. Untertitel https://api-tvthek.orf.at/assets/subtitles/0155/83/26bf214c2156d38e6b53c85417da70b1367edf61.ttml schreiben nach /home/oc/storage/Videos/DE/TODO
. Untertitel-Datei wurde geschrieben
. File: /home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.ttml
java.lang.Exception: Unknown TTML file version
	at mediathek.tool.TimedTextMarkupLanguageParser.parse(TimedTextMarkupLanguageParser.java:206) ~[MediathekView.jar:?]
	at mediathek.tool.MVSubtitle.convertSubtitle(MVSubtitle.java:85) ~[MediathekView.jar:?]
	at mediathek.tool.MVSubtitle.writeSubtitle(MVSubtitle.java:70) ~[MediathekView.jar:?]
	at mediathek.controller.starter.ExternalProgramDownload.lambda$startSubtitleFileDownload$2(ExternalProgramDownload.java:210) ~[MediathekView.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
. Untertitel-Datei wurde konvertiert.
. [Download ist fertig und war fehlerhaft, Programmset: Linux Speichern, Ziel: /home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4, Startzeit: 2023-06-17T16:08:17.979265899, Endzeit: 2023-06-17T16:08:26.03917885, Restarts: 0, Dauer: 8 s, URL: https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8, Programmaufruf: /home/oc/opt/bin/ffmpeg -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" -i https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8 -c copy -bsf:a aac_adtstoasc /home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4, Programmaufruf[]: /home/oc/opt/bin/ffmpeg<>-user_agent<>"Mozilla/5.0<>(Windows<>NT<>10.0;<>Win64;<>x64;<>rv:109.0)<>Gecko/20100101<>Firefox/109.0"<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>/home/oc/storage/Videos/DE/TODO/ZIB_2-ZIB_2-1359915367.mp4]

```

**Comment by DaDirnbocher** [comment]
Do not use spaces in the user-agent.

**Comment by Ottaviocr** [comment]
> Do not use spaces in the user-agent.

Do you mean inside the brackets?

Programmaufruf: /home/oc/opt/bin/ffmpeg -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0"

I also tried -user_agent "Moozilla", "mozilllla", "X". Nothing seems to work. I took all the examples from the forum.

**Comment by DaDirnbocher** [comment]
`/usr/bin/ffmpeg<>-user_agent<>X<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<><ZIelpfad>`

Mein Aufruf unter Mint mit MV 13.9.1 und dieser ZIB funktioniert (ersetze <ZIelpfad> durch einen geeigneten Pfad.

**Comment by DaDirnbocher** [comment]
My Settings:

![image](https://github.com/mediathekview/MediathekView/assets/11771553/c616bffd-4d5a-4170-ac4d-36343427364c)

**Comment by vitusson** [comment]
Ich kann das unter Debian Buster auch nicht reproduzieren. Download läuft ganz normal mit
`/usr/bin/ffmpeg<>-user-agent<>"MozillaFirefox"<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14182825_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>/mnt/Filme/ZIB 2.mp4`

**Comment by styroll** [comment]
>@Ottaviocr sagte: I also tried -user_agent "Moozilla", "mozilllla", "X". Nothing seems to work. I took all the examples from the forum.

As my [manual in the forum](https://forum.mediathekview.de/post/26990) said: spaces in user agent are not allowed using Linux, and you have to delete the entry of the failed download in the tab "Downloads" and restart your ZIB-Download.

Please update to the most actual version of ffmpeg available and check the path of ffmpeg on your system:
"/home/oc/opt/bin/ffmpeg" instead of "/opt/bin/ffmpeg".

**Comment by Ottaviocr** [comment]
> Warum der ungewöhnliche Pfad /opt/bin/ffmpeg bei dir?

Denn das sind die neuesten "static builds" von https://johnvansickle.com/ffmpeg/.

**Comment by Ottaviocr** [comment]
Es scheint jetzt mit  `-user_agent X`  zu funktionieren, ohne Klammern um `X`.

`. [Download ist fertig und hat geklappt, Programmset: Linux Speichern, Ziel: /home/oc/storage/Videos/DE/TODO/ZIB-ZIB_13_00-1852537954.mp4, Startzeit: 2023-06-19T15:57:14.186027984, Endzeit: 2023-06-19T15:59:24.239711729, Restarts: 0, Dauer: 130 s, URL: https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14183128_0001_Q6A.mp4/playlist.m3u8, Programmaufruf: /home/oc/opt/bin/ffmpeg -user_agent X -i https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14183128_0001_Q6A.mp4/playlist.m3u8 -c copy -bsf:a aac_adtstoasc /home/oc/storage/Videos/DE/TODO/ZIB-ZIB_13_00-1852537954.mp4, Programmaufruf[]: /home/oc/opt/bin/ffmpeg<>-user_agent<>X<>-i<>https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14183128_0001_Q6A.mp4/playlist.m3u8<>-c<>copy<>-bsf:a<>aac_adtstoasc<>/home/oc/storage/Videos/DE/TODO/ZIB-ZIB_13_00-1852537954.mp4]`

**Comment by styroll** [comment]
>@Ottaviocr sagte: Es scheint jetzt mit -user_agent X zu funktionieren, ohne Klammern um X.

Von Klammern war je nie die Rede. Falls du die Anführungszeichen meintest: Das müssen "gerade" Anführungszwichen sein; wenn man die aus der Anleitung – wie empfohlen – kopiert, hat man keine Probleme…

Übrigens: Solche Probleme gehören ins Forum, nicht hierher…
