### ISSUE TITLE
Absturz nach Update auf 14.1.0

### ISSUE THREAD

**Issue by Handkep** [mediathekview/MediathekView#748]
Nach dem Update auf 14.1.0 wird direkt nach jedem Start folgende Fehlermeldung angezeigt.
```java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.deleteAll()" because "writer" is null
	at mediathek.gui.tasks.LuceneIndexWorker.doInBackground(LuceneIndexWorker.java:91)
	at mediathek.gui.tasks.LuceneIndexWorker.doInBackground(LuceneIndexWorker.java:21)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
wenn man auf "OK" clickt, wird MV geschlossen.

**Comment by Handkep** [comment]
Ich habe als Workaround MV deinstalliert und MV 14.0.0 installiert. Funktioniert so wie vorher.

**Comment by derreisende77** [comment]
Welches OS nutzt Du?

**Comment by derreisende77** [comment]
Siehe hierzu auch [diesen Link](https://forum.mediathekview.de/topic/5811/update-von-java-client-14-0-0-auf-14-1-0-problem/5).

**Comment by Handkep** [comment]
> Welches OS nutzt Du?

Win11 64bit

**Comment by derreisende77** [comment]
Beende mal bitte MV, lösche im `.mediathek3`-Ordner den Ordner `mv_index`. Danach neu starten.
Alternativ wie im Forum Link beschrieben mit MV 14.0 Lucene deaktivieren, MV 14.1 installieren und danach neu aktivieren.

**Comment by derreisende77** [comment]
Und wie ist der Stand?

**Comment by ossilator** [comment]
> lösche im .mediathek3-Ordner den Ordner mv_index

bei mir hat der workaround einwandfrei funktioniert. wäre schon ganz nett, das zu automatisieren ...

**Comment by derreisende77** [comment]
@ossilator Ich hatte das anders umgesetzt und als workaround für einen erfolgreicher Neustart die moderne Suche erst einmal deaktiviert. Ich werde das Löschen des Ordners aber noch einbauen.

**Comment by derreisende77** [comment]
@ossilator ist nun drin.
